### ISSUE TITLE
Smaller banner for exhibit pages

### ISSUE THREAD

**Issue by alexdryden** [UIUCLibrary/ksharp#16]
The current banner size makes navigation through exhibits a bit difficult because you have to scroll down to see the content. The Michigan site we were using as inspiration does away with the large banner inside the exhibits and opts for a smaller, university branding [https://apps.lib.umich.edu/online-exhibits/exhibits/show/translation-memory](https://apps.lib.umich.edu/online-exhibits/exhibits/show/translation-memory). 

I think makes for a more approachable exhibit and is something we should try to replicate. My first idea was to make separate entries in theme.ini for homepage banner and content page banners. Then test in `layout.phtml` to see which banner to use  based on if the current page is set as the homepage.  

@Bosterm any other ideas on how to implement?

**Comment by Bosterm** [comment]
@alexdryden Were you still planning on taking care of this issue?

Unfortunately I don't have any particular ideas about implementation, but if you feel like you need someone to bounce ideas off of, let me know. I'm happy to do some investigating.
