### ISSUE TITLE
Make heading language more universal 

### ISSUE THREAD

**Issue by alexdryden** [UIUCLibrary/ksharp#20]
Because some users would like to use the theme to organize sub-units (rather than a unit managing exhibits), it would be nice if the language were a bit more generic (e.g., Exhibit Contents=>Contents).

**Comment by Bosterm** [comment]
Ideally the best way to do this, in my mind, would be to let the user be able to set the title for each time the block is used. So the block editor could have a text field to set the title. Unfortunately, I'm not sure how doable that is.

**Comment by alexdryden** [comment]
Oh, I hadn't considered that but I bet it would be possible by just adding it to the form [here](https://github.com/UIUCLibrary/Mason/blob/8c21ed0fddb2568adaf64160411d31323a027c32/src/Site/BlockLayout/ExhibitContents.php#L163-L194) and then passing the text to the view.
