### ISSUE TITLE
Private items throw error

### ISSUE THREAD

**Issue by alexdryden** [UIUCLibrary/ksharp#22]
When a private item is on a page, non-logged in users see an error.

**Comment by Bosterm** [comment]
Minor addendum, this seems to happen when the private item is in an item showcase, but not when the item is embedded as a media embed.

**Comment by Bosterm** [comment]
Another addendum, this appears to be an error with other themes, so I suspect this is an Omeka S internal bug, not a bug of our theme.

**Comment by alexdryden** [comment]
Weird, I'm still getting it in media embed blocks as well. But also found it in other themes so going to close it here and open an issue in the main repo.
